### ISSUE TITLE
Lizalfos Crash

### ISSUE THREAD

**Issue by erindalc** [Sunconure11/dungeon-mobs#21]
Peacefully existing in my singleplayer world, random crash.

https://gist.github.com/erindalc/1ee45074ca0c7185686605acfdcb20c3

Version: 5.4.0
Forge: 14.23.4.2739

I disabled the Lizalfos in the config and turned on forge's delete erroring entities, which fixed the problem.

**Comment by BlackJar72** [comment]
This has already been mentioned (though attached to another thread).  Actually, I have no idea how to fix it, though it has been a problem since long before I started working on this (I use to turn lizalfos off in the GnomeWorks versions for just this reason).

**Comment by BlackJar72** [comment]
Perhaps it would be possible to detect the error and have them give up, de-linking the "twins" in stead of crashing?

**Comment by Sunconure11** [comment]
Hm, since it'll likely be a bit before I contribute any major code to this, why not ask around here for some aid? @BlackJar72 

http://www.minecraftforge.net/forum/forum/70-modder-support/

http://discord.gg/moddedmc

https://discord.mcmoddev.com/

**Comment by BlackJar72** [comment]
I've just uploaded a version where this is hopefully fixed, but I'm not closing the issue for now -- the rarity of the crash makes practically impossible to fully test.
