### ISSUE TITLE
Console spam from EntitySoniceBoom

### ISSUE THREAD

**Issue by iamtpage** [Sunconure11/dungeon-mobs#25]
I get lots of this in the console when fighting some of the dungeon mobs:
```
> [19:01:10] [Server thread/INFO] [STDOUT]: [com.gw.dm.projectile.EntitySonicBoom:func_70106_y:294]: Sonic boom died!
```

**Comment by BlackJar72** [comment]
Oops, left in some debug code.  I should be fixed now as soon as Curse finishes approving the new patch version.
