### ISSUE TITLE
encountering an illithid crashes a dedicated server with nosuchmethoderror

### ISSUE THREAD

**Issue by kreezxil** [Sunconure11/dungeon-mobs#27]
Server Crash Reports:
http://paste.ubuntu.com/p/kZyYdHvFfd/
http://paste.ubuntu.com/p/VdTdv8rft9/

**Comment by Sunconure11** [comment]
@BlackJar72 Mod is calling for something that does not exist on the server-end, might want to check proxy classes. I'll start working on code + new textures for this mod when I can unfuck my sleep at this point.

**Comment by BlackJar72** [comment]
I've been gone a few days to visit my sister.  I'll try to look at this when I can.

**Comment by BlackJar72** [comment]
It looks like the function in questions is armorItemInSlot() -- which is weird, but maybe only used for rendering armor (in vanilla)?  I have one idea I can try, if that doesn't work I'm not sure what to do.

**Comment by kreezxil** [comment]
In Eclipse there is a launch server option, if your using IDEA there should be a similar option. That particular server is the same as when a dedicated server runs.

**Comment by BlackJar72** [comment]
I never noticed the launch server option -- I'll look into that (though it would still require a client to test).

**Comment by BlackJar72** [comment]
I only know of one other way to do what it was doing -- I'll probably release the bug fix tomorrow.  I probably won't be adding the other enhancement I was thinking of because put simply if I do much modding it will probably Climatic Biomes rather than Dungeon Mobs.

**Comment by kreezxil** [comment]
so what I do in eclipse. I launch the server. then after the server is
launched. I go back to the id and launch the client.

**Comment by Sunconure11** [comment]
I've pushed forth Blackjar's bugfix. Let me know if it works @kreezxil

**Comment by Sunconure11** [comment]
Fixed.
