### ISSUE TITLE
Configurable Spawn Rates

### ISSUE THREAD

**Issue by crazyirishwrencher** [Sunconure11/dungeon-mobs#28]
Love the models, but I pretty much never see any of the mobs in game. Not sure if something else is messing with spawn rates or if DMR mobs are supposed to be exceedingly rare. Anyway, configurable spawn rates would be helpful. Either per mob or maybe as a ratio against other spawns. Thanks for looking!

**Comment by BlackJar72** [comment]
Its funny, I have no trouble finding them in survival (though I'm trying **_not_** to find them).  Perhaps its not the spawn rate at all but the spawn requirements; they all have to be at a certain Y or below and not see the sky.  Maybe the ability to turn the requirements off would give more of what you want?

**Comment by crazyirishwrencher** [comment]
That would be work.

**Comment by BlackJar72** [comment]
I'll see when / if I get some extra time -- it shouldn't be hard, just that I have a lot of other things I need to be doing more.

**Comment by crazyirishwrencher** [comment]
Well, we appreciate what you've already put into it.

**Comment by BlackJar72** [comment]
Its done.  There is a now a special config file "dungeonmobs/spawn_rules.cfg" which can both modify the vanilla-based spawning rule (chance, min, and max) and turn the special spawning rules on or off.  For those with a death wish dungeon mobs can now be everywhere.

This many be the last thing I do with this in the foreseeable future.  I is in version 5.5.0, and will be available as soon as curse approves it.
