### ISSUE TITLE
Server Crash.

### ISSUE THREAD

**Issue by Mr-Krab** [Sunconure11/dungeon-mobs#29]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3433
- Forge version: 14.23.4.2747
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
- Operating System: Debian 9

- Plugins (27): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, BeanCore, CatClearLag, CommandSync, EconomyLite, GriefPrevention, HuskyCrates, HuskyUI, LuckPerms, Nucleus, PayDay, PlaceholderAPI, ProjectCore, QuestItemHelper, SkyClaims, StackBan, UltimateChat, UniversalMarket, VirtualChest, VirtualTool, Wasted, WorldEdit, spark
- Mods (52): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AI Improvements, Auto Crafter, Better Questing, BiblioCraft, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, CustomNPCs, Dungeon Mods, Ex Nihilo Creatio, Fishing Net Mod, Hammer Core, HoloInventory, Immersive Engineering, Immersive Tech, InstantUnify, Iron Chest, ItemPhysic, Just Enough Items, LagGoggles, Mantle, McJtyLib, Mekanism, MrCrayfish's Furniture Mod, Parachronology, QuestUtils, Quick Leaf Decay, Redstone Arsenal, Redstone Flux, Solar Flux Reborn, Standard Expansion, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, UniDict, VanillaFix, WanionLib

**Issue Description**
If you break a trap with blades in the creativity mode, then the console will have a lot of errors. One of the monsters attacking the player caused the crash of the server. See logs.

[logs.zip](https://github.com/Sunconure11/dungeon-mobs/files/2356441/logs.zip)

**Comment by BlackJar72** [comment]
The monster is the illithid -- you may need to turn the illithid off in the config.

I don't think I'll be able to fix this as I'm don't have a lot of time to put into it.  I'm leaving modding, bit by bit, as there are other things I actually need to work on.  I won't close it or say it won't be fixed though.  Maybe @Sunconure11 will take over more of this or recruit another coder -- this is a pretty serious problem.

**Comment by Mr-Krab** [comment]
I could not quickly disable it in the config, since the mods usually do not have a configuration reboot command. But I have on my server a plugin Nucleus, which allows me to block the spawn of certain creatures. I hope that this problem will be solved. Other errors are caused by a conflict with Sponge and Sponge developers are already working on this problem.

**Comment by Sunconure11** [comment]
I'll push forth Blackjar's fix first, and if it does not work, let me know.

**Comment by Sunconure11** [comment]
@Mr-Krab It should be on Curse soon. Let me know if it works.

**Comment by Mr-Krab** [comment]
@Sunconure11 I'll tell.

**Comment by Sunconure11** [comment]
@Mr-Krab https://minecraft.curseforge.com/projects/dungeon-mobs-reborn/files/2613929

**Comment by Sunconure11** [comment]
As for taking over the project, I likely will. Though I'd like to figure out how to make the models sane to texture on first. Though I'll fix bugs for a few versions first.

**Comment by Sunconure11** [comment]
I found another way of fixing this, I will push out a new build soon. Please test it, and also test it if you go near it with a helmet of any kind. If it removes the helmet from you, at least that part is still working.

**Comment by Sunconure11** [comment]
https://minecraft.curseforge.com/projects/dungeon-mobs-reborn/files/2614284

See if this build works, once its on curse.

**Comment by Mr-Krab** [comment]
@Sunconure11 I'll wait.

**Comment by Sunconure11** [comment]
I might be able to push out a build today, regardless though. I'm looking over the code and there is a lot of inappropriate use of client-sided stuff.

**Comment by Sunconure11** [comment]
Hm, could you try this build out? I did a minor tweak that may fix things. Or might not. We shall see.

https://www.dropbox.com/s/b3t2jlk6z80v541/dungeonmobs-5.4.7-MC1.12.2.jar?dl=0

**Comment by Sunconure11** [comment]
Okay, ignore that build, I found a possible fix.

**Comment by Sunconure11** [comment]
https://minecraft.curseforge.com/projects/dungeon-mobs-reborn/files/2614751

Try this when curse approves it

**Comment by Sunconure11** [comment]
Assuming this is fixed. Closing, unless others run into this.
