### ISSUE TITLE
Dungeon "Mods" ?

### ISSUE THREAD

**Issue by KenyMylankca** [Sunconure11/dungeon-mobs#30]
![asd](https://user-images.githubusercontent.com/41585837/46548688-7074e400-c8d8-11e8-88e6-c6b0b23ee3f1.PNG)
isnt the mod name "Dungeon Mobs" ? why JEI catches it as "Dungeon Mods" ?

**Comment by BlackJar72** [comment]
Yeah, its a typo.

Not something that causes serious problems, but then something that could be fixed with just a few lines of code, maybe one (not sure of the top of my head).  Thanks for showing.
