### ISSUE TITLE
Cockatrice Not Disableable

### ISSUE THREAD

**Issue by TGDesigner** [Sunconure11/dungeon-mobs#34]
I am having an issue where when I set B:Cockatrice=false in my config, the cockatrice still appears as a spawnable mob. This does not hold true with other mobs I have disabled.

Versions:
Minecraft 1.12.2
Forge 14.23.5.2781
Dungeon Mobs 5.7.0-MC1.12.2

**Comment by BlackJar72** [comment]
Should be fixed now.
