### ISSUE TITLE
Rakshasa server crash

### ISSUE THREAD

**Issue by Aeron216** [Sunconure11/dungeon-mobs#36]
Server crash right after player gets killed by a Rakshasa. 

https://paste.dimdev.org/ikajurutib.rb

Server crashed again right after restarting from that, 
https://paste.dimdev.org/wazaginoco.rb

had to disable the mob from the config in order for the world to be playable again. 

Previously I had already seen those mobs spawn around with no issues (just by exploring around in spectator mode) but it was until now that I've seen it fight something. 
It's a shame that I had to disable such an interesting mob.

**Comment by BlackJar72** [comment]
OK, I need to just chek to make sure it is an EntityLiving before running that code -- I think that should fix it.

**Comment by BlackJar72** [comment]
This should be fixed out ... the magic missile should now be set dead without trying to affect things that are not valid living entities.
