### ISSUE TITLE
Improve textures

### ISSUE THREAD

**Issue by Sunconure11** [Sunconure11/dungeon-mobs#4]
This mod is full of programmer art

**Comment by Sunconure11** [comment]
Will work on this sometime in August.

**Comment by BlackJar72** [comment]
OK, I'll leave you to that.  I'm interested in seeing what you come up with.

**Comment by Sunconure11** [comment]
1. Complete remake of all textures
2. Shading
3. Bit of noise, but not absurd amounts
4. Easter egg textures (so far, two for the beholder)
5. Variants

**Comment by BlackJar72** [comment]
I'm closing this as it has been duplicated elsewhere.
