### ISSUE TITLE
Thaumcraft support

### ISSUE THREAD

**Issue by Sunconure11** [Sunconure11/dungeon-mobs#6]
Give aspects to the mobs

**Comment by BlackJar72** [comment]
I'd have to learn my way around the thaumcraft API.  Probably not right away, but maybe whenever I do anything extensive with this (other than bug fixes).

**Comment by Sunconure11** [comment]
I mean, it wasn't too hard for me and Alexthe666 to figure out. I have an implementation in my own mod you can look at, and if you want to apply it to mobs, check Ice and Fire.

https://github.com/Alex-the-666/Ice_and_Fire/blob/95f4e402ae3214fc37d0f2d40b3407accf17331a/src/main/java/com/github/alexthe666/iceandfire/integration/ThaumcraftCompat.java

https://github.com/Alex-the-666/Ice_and_Fire/blob/95f4e402ae3214fc37d0f2d40b3407accf17331a/src/main/java/com/github/alexthe666/iceandfire/integration/ThaumcraftCompatBridge.java

https://github.com/Alex-the-666/Ice_and_Fire/blob/95f4e402ae3214fc37d0f2d40b3407accf17331a/src/main/java/com/github/alexthe666/iceandfire/IceAndFire.java

**Comment by BlackJar72** [comment]
Well, I haven't "retired" from modding like GnomeWorks has,  However, I've come close and stated I was quitting several times.  You could say I'm semi-"retired" for now, and don't know how much longer I'll be with it.  So I may get around to it, I do when I do.  Easy or hard it does take time, and I'm at a point where I really need to spend less time on such things for many reasons.  So its not that I won't, but I'm not in a hurry to get in everything that everyone might want.  It just when I get around to it, unless someone else wants to take over.

**Comment by BlackJar72** [comment]
I could look into this in the next couple weeks, don't know.  One real problem -- I lack experience in newer version of Thaumcraft (since TC 4), so I'm not really sure what aspects exist or how they should be balanced.

**Comment by Sunconure11** [comment]
https://github.com/Um-Mitternacht/Bewitchment/blob/0882f958c99e900f8d36ffdc714c030a4fd8502e/src/main/java/com/bewitchment/common/integration/thaumcraft/ThaumcraftCompat.java

**Comment by BlackJar72** [comment]
Now, if I could figure out where / how to get a deobf jar or the Thaumcraft API.  What Azanor gives is only source code, which I can't compile against and which will not compile with the rest of Thaumcraft (which Azanor does not provide).

**Comment by BlackJar72** [comment]
The Thaumcraft API will not compile (and will block projects using it from compiling) without:

`thaumcraft.common.lib.utils.InventoryUtils`

Which is not included. @Azanor, @Um-Mitternacht, How does one do this?

**Comment by BlackJar72** [comment]
Doesn't see to do anything.

**Comment by BlackJar72** [comment]
Nope!

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
11 actionable tasks: 10 executed, 1 up-to-date`

Even if it worked, I'd be very reluctant to work on this at all with eclipse all messed up by not recognizing the code I'm referencing. :-/

**Comment by Sunconure11** [comment]
WTF? It worked fine for me...

**Comment by Sunconure11** [comment]
Try setupDecompWorkspace

**Comment by BlackJar72** [comment]
Removed broken reference to DLD api, try re-running the setup, still no good:

`
> Task :compileJava
/home/jared/Documents/src/eclipse/MC1.12.2/DungeonMobs/build/sources/main/java/com/gw/dm/compat/Thaumic.java:12: error: cannot find symbol
        public void aspectRegistrationEvent(AspectRegistryEvent evt) {
                                            ^
  symbol:   class AspectRegistryEvent
  location: class Thaumic
1 error

`

**Comment by Sunconure11** [comment]
I'll see what I can figure out over the next few days, then.

**Comment by BlackJar72** [comment]
Yeah, I tried again with Forge Gradle instead of the installed version, but same results -- it doesn't recognize anything from Thaumcraft.

Even if it did, I really don't like not have Eclipse recognize things and not being able to lauch test runs from Eclipse.

**Comment by Sunconure11** [comment]
There is. Check the threads for them

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1294623-baubles-1-4-6-1-5-2-updated-2018-1-10

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1292130-thaumcraft-6-1-beta26-hotfix

**Comment by BlackJar72** [comment]
The one for Thaumcraft API is not a deobf, it's source code.  But I'll see if that Baubles deobf makes the source code work.

**Comment by BlackJar72** [comment]
Well, that did it.  I just always forget that Baubles is now a thing, and lack of Baubles was causing the whole problem before.  I suspect that it will actually be a lot less work and frustration that getting things set up.

**Comment by BlackJar72** [comment]
Well, I may have finished all the actual code needed for Thaumcraft compatibility.  Can't test it be because just to remind me that reality is definitely not self-consistent the setup that worked perfectly when I went to bed didn't work anymore when I got up -- no complaints about my code, but it now crashes trying to compile the Thaumcraft API.

**Comment by Sunconure11** [comment]
I'll work on it in the next few days

**Comment by BlackJar72** [comment]
I have it working now -- but don't think it should be released until it's been tested without Thaumcraft.

This is one thing that annoys me with Forge, or really with Gradle or the Forge Gradle.  It's so fragile and finicky, you need a whole new directory for every forge update.  (Which lead me to avoid updates.)

**Comment by BlackJar72** [comment]
I'm closing this, as far as I can tell everything works.
